#!/usr/bin/env sh

unset WAYLAND_DISPLAY

export XDG_SESSION_TYPE=wayland
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export MOZ_ENABLE_WAYLAND=1
export MOZ_USE_XINPUT2=1
