cnoremap w! w !sudo tee % >/dev/null

if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME="$HOME/.config" | endif
if empty($XDG_CACHE_HOME) | let $XDG_CACHE_HOME="$HOME/.cache" | endif
set directory=$XDG_CACHE_HOME/vim/swp,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp"
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/after
" let $MYVIMRC=$XDG_CONFIG_HOME/vim/vimrc

" Plugins (junegunn/vim-plug)
call plug#begin('$XDG_CONFIG_HOME/vim/plugged')
Plug 'bling/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'chrisbra/Recover.vim'
Plug 'chriskempson/base16-vim'
Plug 'edkolev/tmuxline.vim'
call plug#end()

" color scheme
set background=dark
set t_Co=256
let base16colorspace=256
colorscheme base16-tomorrow
let g:airline_theme='base16'

" airline
set laststatus=2
set ttimeoutlen=50
set noshowmode
let g:airline_powerline_fonts = 1

" tmuxline
let g:tmuxline_preset = {
	\'a'       : '#S',
	\'win'     : ['#I', '#W'],
	\'cwin'    : ['#I', '#W', '#F'],
	\'z'       : '#H',
	\'options' : {'status-justify' : 'left'}
	\}

set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set list
set number

autocmd FileType * set tabstop=2 | set shiftwidth=2 | set softtabstop=2 | set noexpandtab
autocmd FileType python set tabstop=4 | set shiftwidth=4 | set softtabstop=4 | set expandtab
filetype plugin indent on
syntax on

set cursorline
hi CursorLine ctermbg=18
hi MatchParen cterm=none ctermbg=18 ctermfg=1
