cnoremap w! w !sudo tee % >/dev/null

set background=dark
let base16colorspace=256
colorscheme base16-tomorrow

autocmd FileType * set tabstop=2 | set shiftwidth=2 | set softtabstop=2 | set noexpandtab
autocmd FileType python set tabstop=4 | set shiftwidth=4 | set softtabstop=4 | set expandtab
filetype plugin indent on
syntax on

set cursorline

if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME="$HOME/.config" | endif
if empty($XDG_CACHE_HOME) | let $XDG_CACHE_HOME="$HOME/.cache" | endif
set directory=$XDG_CACHE_HOME/vim/swp,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp"
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/after
" let $MYVIMRC=$XDG_CONFIG_HOME/vim/vimrc
