#!/usr/bin/env sh

alias dmesg='dmesg -H'
alias grep='grep --color=auto'
alias ls='ls -F --color=auto'
alias ll='ls -lAh'
alias rm='echo | xargs -p rm'

alias sudodiff='SUDO_EDITOR="vimdiff" sudoedit'

alias pycalc='python3 -ic "from math import *"'
alias pyserv='python3 -m http.server 7777'

alias clip-copy='xsel --clipboard --input <'
alias clip-paste='xsel --clipboard --output >'

bashisms() {
	checkbashisms -f -p $(grep -IrlE '^#! ?(/usr)?/bin/(env )?sh' "$@")
}
cd() {
	command cd "$@" && ls
}
pacaur() {
	command pacaur "$@"
	(nohup $XDG_BIN_HOME/updates.sh >/dev/null 2>&1 &)
}
wcf() {
	if [ -z "$1" ]; then
		find . | xargs wc -l
	else
		find . -name "*.${1}" | xargs wc -l
	fi
}
