#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
[ -f $XDG_CONFIG_HOME/xdg.sh ] && . $XDG_CONFIG_HOME/xdg.sh

export PATH="$PATH:$XDG_BIN_HOME"
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'

HISTCONTROL=ignoreboth:erasedups
shopt -s histappend
shopt -s autocd

if [ -f /usr/share/git/completion/git-prompt.sh ]; then
	source /usr/share/git/completion/git-prompt.sh
	#GIT_PS1_SHOWDIRTYSTATE=1
	#GIT_PS1_SHOWSTASHSTATE=1
	#GIT_PS1_SHOWUNTRACKEDFILES=1
fi
if [ -f $XDG_CONFIG_HOME/aliases ]; then
	. $XDG_CONFIG_HOME/aliases
fi
if [ -f $XDG_CONFIG_HOME/dircolors ]; then
	eval "$(dircolors $XDG_CONFIG_HOME/dircolors)"
elif [ -f /etc/DIR_COLORS ]; then
	eval "$(dircolors /etc/DIR_COLORS)"
fi

function prompt_gen() {
	let ret=$? # must be first
	local fill=$(printf "%$(tput cols)s\n" | sed "s/ /─/g")
	export PS1="$fill\r[\[\e[1;32m\]\u\e[0;m\]@\e[1;33m\]\h\e[0;m\]::\[\e[1;31m\]\$ret\[\e[0;m\]]\e[1C[\[\e[1;34m\]\${PWD##*/}\[\e[0;m\]\$(__git_ps1 \"::\[\e[1;36m\]%s\[\e[0;m\]\")]\nλ "
}
PROMPT_COMMAND="prompt_gen"

if [ "$TERM" = "linux" ]; then
	_SEDCMD='s/.*\*color\([0-9]\{1,\}\).*#\([0-9a-fA-F]\{6\}\).*/\1 \2/p'
	for i in $(sed -n "$_SEDCMD" $XDG_CONFIG_HOME/X11/Xresources | \
				awk '$1 < 16 {printf "\\e]P%X%s", $1, $2}'); do
		echo -en "$i"
	done
	clear
fi

