#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}
hc emit_hook reload

#xsetroot -solid '#5A8E3A'

# set wm name to LG3D to fix Java issues
hc set wmname LG3D

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-q spawn xsecurelock auth_pam_x11 saver_blank
#hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close_or_remove

# applications
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-Shift-d spawn passmenu
hc keybind $Mod-Return spawn urxvtc
hc keybind $Mod-e spawn pcmanfm

# extra keys
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86AudioLowerVolume spawn volume-adjust.sh down
hc keybind XF86AudioRaiseVolume spawn volume-adjust.sh up
hc keybind XF86AudioMute spawn volume-adjust.sh mute
hc keybind $Mod-XF86AudioMute spawn pavucontrol
hc keybind $Mod-F1 spawn monitor-toggle.sh
hc keybind $Mod-F2 spawn network-restart.sh
hc keybind XF86TouchpadToggle spawn touchpad-toggle.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-b       split   vertical 0.5
hc keybind $Mod-v       split   horizontal 0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep_large=0.05
resizestep_small=0.01
hc keybind $Mod-Control-h       resize left +$resizestep_small
hc keybind $Mod-Control-j       resize down +$resizestep_small
hc keybind $Mod-Control-k       resize up +$resizestep_small
hc keybind $Mod-Control-l       resize right +$resizestep_small
hc keybind $Mod-Control-Left    resize left +$resizestep_large
hc keybind $Mod-Control-Down    resize down +$resizestep_large
hc keybind $Mod-Control-Up      resize up +$resizestep_large
hc keybind $Mod-Control-Right   resize right +$resizestep_large

# tags
tag_names=( "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X" )
tag_keys=( {1..9} 0 )
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]}; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if ! [ -z "$key" ]; then
		hc keybind "$Mod-$key" use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-Shift-comma  move_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1 vertical horizontal max
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-slash       cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set always_show_frame 0 # hide empty frames

hc set frame_bg_active_color '#3b9dff'
hc set frame_bg_transparent 1 # transparent background
hc set frame_transparent_width 3 # empty frame border width

hc set frame_border_width 0 # around all windows in a frame
hc set frame_gap 5 # gap between frames

hc attr theme.background_color '#1d1f21' # match terminal background color
hc attr theme.border_width 3
hc attr theme.inner_width 0 # no inner border
hc attr theme.outer_color '#ffffff' # white outer border
hc attr theme.outer_width 0 # no outer border

hc attr theme.active.color '#3b9dff' # light-blue
hc attr theme.floating.border_width 5 # display a small border of
hc attr theme.floating.outer_width 1 # white around floating windows
hc attr theme.normal.color '#a7a7a7' # grey
hc attr theme.urgent.color '#ffa500' # orange

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|Pinentry)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# load all backgrounds from $XDG_DATA_HOME/feh
feh --bg-scale "${XDG_DATA_HOME:-$HOME/.local/share}/feh"

# find the panel
panel=$HOME/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
	# start it on each monitor
	"$panel" $monitor &
done
