#!/usr/bin/env sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

if [ -f "$XDG_CONFIG_HOME/X11/Xresources" ]; then
	xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
fi

dmenu_path >/dev/null 2>&1 &

exec herbstluftwm >"$XDG_DATA_HOME/xorg/hlwm.log" 2>&1
