#!/usr/bin/env bash

hc() { herbstclient "$@" ;}
hc emit_hook reload

# cleanup old sessions
hc keyunbind   --all
hc mouseunbind --all
hc unrule      --all

# tags
tags="I:1 II:2 III:3 IV:4 V:5 VI:6 VII:7 VIII:8 IX:9 X:0 XI:bracketleft XII:bracketright"
hc rename default "I" || true
key_index=0
for tag in $tags; do
	IFS=':' read -r name key <<EOF
$tag
EOF
	hc add "$name"
	if ! [ -z "$key" ]; then
		hc keybind Mod4-$key       use_index  "$key_index"
		hc keybind Mod4-Shift-$key move_index "$key_index"
	fi
	((key_index=key_index+1))
done

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.background_color $_xrdb_background # match terminal background color
hc attr theme.color $_xrdb_color15 # white
hc attr theme.border_width 3
hc attr theme.inner_width 0 # no inner border
hc attr theme.outer_width 0 # no outer border

hc attr theme.active.color $_xrdb_color4 # blue
hc attr theme.normal.color ${_xrdb_color20:-$_xrdb_color12} # grey (256 vs reg)
hc attr theme.urgent.color $_xrdb_color1 # red

hc set always_show_frame 0 # hide empty frames

hc set frame_bg_transparent 1 # transparent background
hc set frame_transparent_width 3 # empty frame border width

hc set frame_border_width 0 # around all windows in a frame
hc set frame_gap 5 # gap between frames

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc set tree_style '╾│ ├└╼─┐'
hc set wmname LG3D # fix Java issues
hc set auto_detect_monitors 1

# rules
hc rule focus=off # normally do not focus new clients
hc rule class~'(Pinentry)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc unlock # unlock, just to be sure

# monitor setup
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
hc detect_monitors # automatic detection

# load random background
feh --no-fehbg --randomize --recursive --bg-scale "${XDG_DATA_HOME:-$HOME/.local/share}/feh"

# find the panel
panel=${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
	"$panel" $monitor & # start panel on each monitor
done
